<robot name="robot_hanchenhao" xmlns:xacro="http://www.ros.org/wiki/xacro">

  <xacro:property name="PI" value="3.1415926535897931"/>
  <xacro:property name="height3" value="0.15" /> <!-- Link 3 -->
  <xacro:property name="axel_offset" value="0.05" /> <!-- Space btw top of beam and the each joint -->
  <xacro:property name="update_rate" value="20" />
  <!-- Import all Gazebo-customization elements, including Gazebo colors -->
  <xacro:include filename="$(find gazebo_ros_my_robot_description)/urdf/my_robot_plugin.gazebo" />

  <link name="base_link">

    <collision> 
      <geometry>
        <box size="1.0 0.8 0.2"/>
      </geometry>
    </collision>

    <visual>
      <geometry>
        <box size="1.0 0.8 0.2"/>
      </geometry>
      <material name="darkblue">
        <color rgba=".2 .2 .8 1"/>
      </material>
    </visual>

    <inertial>
      <mass value="1"/>
      <inertia
        ixx="1.0" ixy="0.0" ixz="0.0"
        iyy="1.0" iyz="0.0"
        izz="1.0"/>
    </inertial>

  </link>

  <gazebo reference="base_link">
    <material>Gazebo/Blue</material>
  </gazebo>

  <link name="body_link">

    <collision>
      <geometry>
        <cylinder length="1.8" radius="0.30"/>
      </geometry>
    </collision>

    <visual>
      <geometry>
        <cylinder length="1.8" radius="0.30"/>
      </geometry>
      <material name="red">
        <color rgba="1 0 0 1"/>
      </material>
    </visual>

    <inertial>
      <mass value="1"/>
      <inertia
        ixx="1.0" ixy="0.0" ixz="0.0"
        iyy="1.0" iyz="0.0"
        izz="1.0"/>
    </inertial>

  </link>

  <gazebo reference="body_link">
    <material>Gazebo/Red</material>
  </gazebo>

  <link name="wheel_left_link">

    <collision>
      <origin xyz="0 0 0" rpy="1.57 0 0" />
      <geometry>
        <cylinder length="0.2" radius="0.40"/>
      </geometry>

      <surface>
      <friction>
                <ode>
                  <mu>0.8</mu>
                  <mu2>0.8</mu2>
                </ode>
              </friction>
      </surface>

    </collision>

    <visual>
      <origin xyz="0 0 0" rpy="1.57 0 0" />
      <geometry>
        <cylinder length="0.2" radius="0.40"/>
      </geometry>
      <material name="black">
        <color rgba="0 0 0 1"/>
      </material>
    </visual>

    <inertial>
      <origin xyz="0 0 0" rpy="1.57 0 0"/>
      <mass value="1"/>
      <inertia
        ixx="1.0" ixy="0.0" ixz="0.0"
        iyy="1.0" iyz="0.0"
        izz="1.0"/>
    </inertial>

  </link>

  <gazebo reference="wheel_left_link">
    <material>Gazebo/Black</material>
  </gazebo>

  <link name="wheel_right_link" >

    <collision>
      <origin xyz="0 0 0" rpy="1.57 0 0" />
      <geometry>
        <cylinder length="0.2" radius="0.40"/>
      </geometry>

      <surface>
      <friction>
                <ode>
                  <mu>0.8</mu>
                  <mu2>0.8</mu2>
                </ode>
              </friction>
      </surface>

    </collision>

    <visual>
      <origin xyz="0 0 0" rpy="1.57 0 0" />
      <geometry>
        <cylinder length="0.2" radius="0.40"/>
      </geometry>
      <material name="black">
        <color rgba="0 0 0 1"/>
      </material>
    </visual>

    <inertial>
      <origin xyz="0 0 0" rpy="1.57 0 0"/>
      <mass value="1"/>
      <inertia
        ixx="1.0" ixy="0.0" ixz="0.0"
        iyy="1.0" iyz="0.0"
        izz="1.0"/>
    </inertial>

  </link>

  <gazebo reference="wheel_right_link">
    <material>Gazebo/Black</material>
  </gazebo>

    <gazebo reference="body_link">
    <material>Gazebo/Red</material>
  </gazebo>

  <link name="bwheel_left_link">

    <collision>
      <origin xyz="0 0 0" rpy="1.57 0 0" />
      <geometry>
        <cylinder length="0.2" radius="0.40"/>
      </geometry>

      <surface>
      <friction>
                <ode>
                  <mu>0.8</mu>
                  <mu2>0.8</mu2>
                </ode>
              </friction>
      </surface>

    </collision>

    <visual>
      <origin xyz="0 0 0" rpy="1.57 0 0" />
      <geometry>
        <cylinder length="0.2" radius="0.40"/>
      </geometry>
      <material name="black">
        <color rgba="0 0 0 1"/>
      </material>
    </visual>

    <inertial>
      <origin xyz="0 0 0" rpy="1.57 0 0"/>
      <mass value="1"/>
      <inertia
        ixx="1.0" ixy="0.0" ixz="0.0"
        iyy="1.0" iyz="0.0"
        izz="1.0"/>
    </inertial>

  </link>

  <gazebo reference="bwheel_left_link">
    <material>Gazebo/Black</material>
  </gazebo>

  <link name="bwheel_right_link" >

    <collision>
      <origin xyz="0 0 0" rpy="1.57 0 0" />
      <geometry>
        <cylinder length="0.2" radius="0.40"/>
      </geometry>

      <surface>
      <friction>
                <ode>
                  <mu>0.8</mu>
                  <mu2>0.8</mu2>
                </ode>
              </friction>
      </surface>

    </collision>

    <visual>
      <origin xyz="0 0 0" rpy="1.57 0 0" />
      <geometry>
        <cylinder length="0.2" radius="0.40"/>
      </geometry>
      <material name="black">
        <color rgba="0 0 0 1"/>
      </material>
    </visual>

    <inertial>
      <origin xyz="0 0 0" rpy="1.57 0 0"/>
      <mass value="1"/>
      <inertia
        ixx="1.0" ixy="0.0" ixz="0.0"
        iyy="1.0" iyz="0.0"
        izz="1.0"/>
    </inertial>

  </link>

  <gazebo reference="bwheel_right_link">
    <material>Gazebo/Black</material>
  </gazebo>


  <link name="hand_left_link" >

    <collision>
      <origin xyz="0.25 -0.1 0" rpy="0 1.57 0" />
      <geometry>
        <box size="0.1 0.2 0.6"/>
      </geometry>
    </collision>

    <visual>
      <origin xyz="0.25 -0.1 0" rpy="0 1.57 0" />
      <geometry>
        <box size="0.1 0.2 0.6"/>
      </geometry>
      <material name="yellow">
        <color rgba="1 1 0 1"/>
      </material>
    </visual>

    <inertial>
      <origin xyz="0.25 -0.1 0" rpy="0 1.57 0" />
      <mass value="1"/>
      <inertia
        ixx="1.0" ixy="0.0" ixz="0.0"
        iyy="1.0" iyz="0.0"
        izz="1.0"/>
    </inertial>

  </link>

  <gazebo reference="hand_left_link">
    <material>Gazebo/Yellow</material>
  </gazebo>

  <link name="hand_right_link">

    <collision>
      <origin xyz="0.25 0.1 0" rpy="0 1.57 0" />
      <geometry>
        <box size="0.1 0.2 0.6"/>
      </geometry>
    </collision>

    <visual>
      <origin xyz="0.25 0.1 0" rpy="0 1.57 0" />
      <geometry>
        <box size="0.1 0.2 0.6"/>
      </geometry>
      <material name="yellow">
        <color rgba="1 1 0 1"/>
      </material>
    </visual>

    <inertial>
      <origin xyz="0.25 0.1 0" rpy="0 1.57 0" />
      <mass value="1"/>
      <inertia
        ixx="1.0" ixy="0.0" ixz="0.0"
        iyy="1.0" iyz="0.0"
        izz="1.0"/>
    </inertial>

  </link>

  <gazebo reference="hand_right_link">
    <material>Gazebo/Yellow</material>
  </gazebo>

  <link name="head_link">

    <collision>
      <geometry>
        <sphere radius="0.4"/>
      </geometry>
    </collision>

    <visual>
      <geometry>
        <sphere radius="0.4"/>
      </geometry>
      <material name="yellow">
        <color rgba="1 1 0 1"/>
      </material>
    </visual>

    <inertial>
      <mass value="1"/>
      <inertia
        ixx="1.0" ixy="0.0" ixz="0.0"
        iyy="1.0" iyz="0.0"
        izz="1.0"/>
    </inertial>

  </link>

   <!-- Hokuyo Laser -->
  <link name="hokuyo_link">
    <collision>
      <origin xyz="0 0 0" rpy="0 0 0"/>
      <geometry>
    <box size="0.1 0.1 0.1"/>
      </geometry>
    </collision>

    <visual>
      <origin xyz="0 0 0" rpy="0 0 0"/>
      <geometry>
         <mesh filename="package://gazebo_ros_my_robot_description/meshes/hokuyo.dae"/>
      </geometry>
    </visual>

    <inertial>
      <mass value="1e-5" />
      <origin xyz="0 0 0" rpy="0 0 0"/>
      <inertia ixx="1e-6" ixy="0" ixz="0" iyy="1e-6" iyz="0" izz="1e-6" />
    </inertial>
  </link>

  <gazebo reference="head_link">
    <material>Gazebo/Yellow</material>
  </gazebo>

  <joint name="joint_left_wheel" type="continuous">
    <parent link="base_link"/>
    <child link="wheel_left_link"/>
    <origin xyz="0.5 0.5 0" rpy="0 0 0" />
    <axis xyz="0 1 0"/>
    <dynamics damping="0.7" friction="0.0"/>
  </joint>

  <joint name="joint_right_wheel" type="continuous">
    <parent link="base_link"/>
    <child link="wheel_right_link"/>
    <origin xyz="0.5 -0.5 0" rpy="0 0 0" />
    <axis xyz="0 1 0"/>
    <dynamics damping="0.7" friction="0.0"/>
  </joint>

    <joint name="joint_left_bwheel" type="continuous">
    <parent link="base_link"/>
    <child link="bwheel_left_link"/>
    <origin xyz="-0.5 0.5 0" rpy="0 0 0" />
    <axis xyz="0 1 0"/>
    <dynamics damping="0.7" friction="0.0"/>
  </joint>

  <joint name="joint_right_bwheel" type="continuous">
    <parent link="base_link"/>
    <child link="bwheel_right_link"/>
    <origin xyz="-0.5 -0.5 0" rpy="0 0 0" />
    <axis xyz="0 -1 0"/>
    <dynamics damping="0.7" friction="0.0"/>
  </joint>


  <joint name="joint_base" type="fixed">
    <parent link="base_link"/>
    <child link="body_link"/>
    <origin xyz="0 0 1" rpy="0 0 0" />
  </joint>

  <joint name="joint_left_hand" type="continuous">
    <parent link="body_link"/>
    <child link="hand_left_link"/>
    <origin xyz="0 0.5 0.2" rpy="0 0 0" />
    <axis xyz="0 1 0"/>
    <dynamics damping="0.7" friction="0.0"/>
  </joint>

  <joint name="joint_right_hand" type="continuous">
    <parent link="body_link"/>
    <child link="hand_right_link"/>
    <origin xyz="0 -0.5 0.2" rpy="0 0 0" />
    <axis xyz="0 -1 0"/>
    <dynamics damping="0.7" friction="0.0"/>
  </joint>

  <joint name="joint_head" type="prismatic">
    <parent link="body_link"/>
    <child link="head_link"/>
    <limit effort="10" lower="-0.1" upper="0.1" velocity="10"/>
    <origin xyz="0 0 1" rpy="0 0 0" />
    <axis xyz="0 0 1"/>
    <dynamics damping="0.7" friction="0.0"/>
  </joint>


  <joint name="hokuyo_joint" type="fixed">
    <axis xyz="0 1 0" />
    <origin xyz="0.4 0 ${height3 - axel_offset/2}" rpy="0 0 0"/>
    <parent link="base_link"/>
    <child link="hokuyo_link"/>
  </joint>



  <transmission name="tran1">
    <type>transmission_interface/SimpleTransmission</type>
    <joint name="joint_left_hand"/>
    <actuator name="motor1">
      <hardwareInterface>EffortJointInterface</hardwareInterface>
      <mechanicalReduction>1</mechanicalReduction>
    </actuator>
  </transmission>

  <transmission name="tran2">
    <type>transmission_interface/SimpleTransmission</type>
    <joint name="joint_right_hand"/>
    <actuator name="motor2">
      <hardwareInterface>EffortJointInterface</hardwareInterface>
      <mechanicalReduction>1</mechanicalReduction>
    </actuator>
  </transmission>

  

</robot>
